### PR TITLE
Fix #7 by changing newproject to use []

### LINKED ISSUE #7: The newproject script is broken because it uses [[]] while running in sh
At some point during our initial development, we changed `newproject` to run in `sh` instead of `bash` because we thought it did not use anything bash-specific. We were wrong however, since it uses `[[]]`.

### PR DESCRIPTION
**Pull request by avdstaaij**
This fixes #7.
If the tests in `newproject` are rewritten to not require `[[]]`, that could of course replace this PR.

### CODE REVIEW

**Comment by Thyrum** [comment]
This can quite easily be written to only use `[]` thus I don't think we should require `bash`.

**Review by Thyrum — APPROVED** [review]
We can easily rewrite this to only use `[]` and thus not require `bash`. Until we do, this is a good fix.

**Comment by Thyrum** [comment]
I think this can now be merged. Please do make sure e239fba does not get to master.

**Comment by avdstaaij** [comment]
Now `newproject` fails with:
`./newproject: 25: read: Illegal option -n`
If you try to initialize in a directory that already has files. That should be fixed too if we step away from bash.

**Comment by Thyrum** [comment]
> Now `newproject` fails with:
> `./newproject: 25: read: Illegal option -n`
> If you try to initialize in a directory that already has files. That should be fixed too if we step away from bash.

It seems that the `-n` option is not in the POSIX standard. We could remove the `-n` option but this would result in the user having to press enter instead of just continuing on the first keystroke. Since I like the current behavior more, I agree with just using `bash`, meaning we merge e239fba into master.

**Comment by avdstaaij** [comment]
e239fba9f6cb114460ed64a17c6ccf8af95216b8 has been merged into master and the other branches have been rebased on top of it.

**Pull request closed without merging**
